"""empty message

Revision ID: b8963987c771
Revises: 
Create Date: 2018-07-17 15:30:43.282641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8963987c771'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aulas',
    sa.Column('idAula', sa.Integer(), nullable=False),
    sa.Column('curso', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('tituloAula', sa.Text(), nullable=True),
    sa.Column('descricaoAula', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['cursos.idCurso'], ),
    sa.PrimaryKeyConstraint('idAula')
    )
    op.create_table('videos',
    sa.Column('idVideo', sa.Integer(), nullable=False),
    sa.Column('aula', sa.Integer(), nullable=True),
    sa.Column('videoEndereco', sa.Text(), nullable=True),
    sa.Column('descricaoVideo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['aula'], ['aulas.idAula'], ),
    sa.PrimaryKeyConstraint('idVideo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('aulas')
    # ### end Alembic commands ###
